---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "run anscap"
      anscap:
        src: '/tmp/build/api.tar.gz'
        app_name: "api"
        deploy_dir: "/tmp/api"
      register: result

    - debug:
        var: result
